// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3033_1_HW3_.Data;

#nullable disable

namespace _3033_1_HW3_.Migrations
{
    [DbContext(typeof(DBCon))]
    [Migration("20221011144706_create_db_receipt")]
    partial class create_db_receipt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");
#pragma warning restore 612, 618
        }
    }
}
